version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: maquinas_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      - DATABASE_URL=mysql://root:123456@mysql:3306/maquinas_db

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
